// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MrAdviceTest;

#nullable disable

namespace MrAdviceTest.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MrAdviceTest.FeatureToggleModel", b =>
                {
                    b.Property<string>("ToggleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Toggle")
                        .HasColumnType("bit");

                    b.HasKey("ToggleId");

                    b.ToTable("featuretoggles");
                });
#pragma warning restore 612, 618
        }
    }
}
